---
all:
  children:
    target_server:
      hosts:
        hc9t06914.itcs.hpecorp.net:
          #remote_server
          ansible_ssh_user: '<host_user_name>' 
          ansible_ssh_pass: '<host_user_password>'
          ansible_sudo_pass: '<host_user_sudo_password>' 
          
          server_type: '<snaplogic/kafka>' #snaplogic/kafka

          store_directory: '/home/{{ansible_date_time.date}}/{{server_type}}' #this is a suggestion using ansible built in date, corrrect this path
          
          old_certificate_path: '/etc/snaplogic/jcc-serverkeys.jks' #change this to reflect correct path

          common_name: '<common_name>.its.hpecorp.net' #ends with its.hpecorp.net
          alias_name: '<alias_name>' #or friendly name
          

          #for snaplogic only:
          storekey_pass_path: '/etc/snaplogic/jcc-serverkeys.pass' #change this to reflect correct path
          old_trustca_path: '/opt/snaplogic/pkgs/jdk-11.0.8+10-jre/lib/security/cacerts' #change this to reflect correct path
          production: False # set to true to run the script that put snaplogic into maintenance mode
          
          #for kafka only:
          storekey_pass: '<password_for_keystore>' #at least 6 chars, for kafka
          restart_server: False #set to True if server needs to restart
          
  vars:
    #for phase 1
    local_store_directory: '/home/{{ansible_date_time.date}}/{{server_type}}' #this is a suggestion, correct this path
    delete_local_file: False # set to True to remove local files once done
    ansible_become_pass: '<sudo_password>' #password of localhost sudo

    VAULT_ADDR: https://vault.docker.hpecorp.net:443
    vault_directory: 'secret/horizon/hoang/{{ansible_date_time.date}}/{{server_type}}' #location to store secrets, this is a suggestion, correct this path
    vault_token: <github-token> #token from Github to access Vault
    HPE_Private_Root_vault: 'secret/horizon/hoang' #directory where HPE Private CA and Root CA is stored, don't change this. Update value in this path when HPE Private CA or Root CA is changed