---
- name: test_absent_on_awx
  hosts: 192.168.1.64
  become: yes
  tasks:
    - name: running snaplogic flow
      block:
      - name: test whoami
        shell: whoami
        register: whoami_return
      - name: debug
        debug:
          msg: "{{whoami_return}}"
      - name: create directory for testing
        file:
          path: '{{store_directory}}'
          state: directory
      - name: create file by copy
        copy:
          dest: "{{store_directory}}/{{item.filepath}}"
          content: "{{item.filecontent}}"
        with_items:
          - {filepath: 'ca.cer', filecontent: 'testing value cho vui nek'}
      - name: delete the directory
        file:
          path: '{{store_directory}}'
          state: absent
        when: delete_file
      delegate_to: localhost
